# Generated by Django 4.2.11 on 2026-09-19 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('COURS', 'Cours'), ('EBOOK', 'Ebook'), ('DATASET', 'Dataset'), ('CARTE', 'Carte / ressource cartographique'), ('PRESTATION', 'Prestation de conseil'), ('CODE_SOURCE', 'Code source')], default='COURS', max_length=20)),
                ('revenue_model', models.CharField(choices=[('ONE_TIME', 'Paiement unique'), ('SUBSCRIPTION', 'Abonnement mensuel'), ('DONATION', 'Don libre'), ('PER_CHAPTER', 'Accès par chapitre')], default='ONE_TIME', max_length=20)),
                ('price', models.PositiveIntegerField(default=0, help_text='Prix en centimes (0 si don libre)')),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Compétences séparées par des virgules', max_length=200)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('credibility_score', models.FloatField(default=0.0, help_text='Score de Crédibilité Scientifique (SCS) : calculé sur publications, citations, notes, interactions')),
                ('google_scholar_url', models.URLField(blank=True, help_text='Pour import futur des publications via DOI')),
                ('badges', models.ManyToManyField(blank=True, related_name='profiles', to='banoma_api.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField(help_text='Montant total payé, en centimes')),
                ('platform_commission', models.PositiveIntegerField(help_text='Part BANOMA (30 %), en centimes')),
                ('creator_revenue', models.PositiveIntegerField(help_text='Part créateur (70 %), en centimes')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='banoma_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIPLOMA', 'Diplôme'), ('CERTIFICATION', 'Certification'), ('PUBLICATION', 'Publication scientifique'), ('PROJECT', 'Projet')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier, si applicable', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='banoma_api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant en centimes')),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money (Wave / Orange Money / Moov)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='banoma_api.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
